services:
  backend:
    build: .
    container_name: flight-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/FlightManagementSystem
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1077225941
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      - POSTGRES_DB=FlightManagementSystem
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1077225941
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
